name: 'Download Covid Data'

#Run at Midnight every day and when triggered
on:
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * *'

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
#Checkout Branch
      - name: checkout repo  
        uses: actions/checkout@v2
# Setup Python
      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
#Run file to download and process covid data csv      
      - name: Download data
        run: python ../../download_latest_covid_data.py
